openapi: 3.0.0
info:
  title: Metacomposite
  version: '1.0'
  description: Returns posts from multiple feeds
servers:
  - url: 'http://localhost:3000'
paths:
  '/feeds/{feedID}':
    parameters:
      - schema:
          type: string
        name: feedID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feed'
      operationId: get-feeds-feedID
      description: Get a feed by ID
  '/feeds/{feedID}/posts':
    parameters:
      - schema:
          type: string
        name: feedID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  feed:
                    $ref: '#/components/schemas/Feed'
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
      operationId: get-feeds-feedID-posts
      description: Get posts associated with the feed
  '/groups/{groupID}':
    parameters:
      - schema:
          type: string
        name: groupID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
      operationId: get-group-groupID
      description: Get a group by ID
  '/groups/{groupID}/posts':
    parameters:
      - schema:
          type: string
        name: groupID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/Group'
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      operationId: get-group-groupID-posts
      description: Get posts associated with a group
  '/groups/{groupID}/feeds':
    parameters:
      - schema:
          type: string
        name: groupID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/Group'
                  feeds:
                    type: array
                    items:
                      $ref: '#/components/schemas/Feed'
      operationId: get-groups-groupID-feeds
      description: Get feeds associated with a group
  /groups:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
      operationId: get-groups
      description: Get all groups
  /feeds:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feed'
      operationId: get-feeds
      description: Get all feeds
  /feeds/posts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
              examples: {}
      operationId: get-feeds-posts
      description: Get all posts from all feeds
components:
  schemas:
    Post:
      title: Post
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        content:
          type: string
        link:
          type: string
        imageURL:
          type: string
        feedID:
          type: string
      required:
        - title
        - description
        - content
        - link
        - feedID
    Feed:
      title: Feed
      type: object
      properties:
        ID:
          type: string
        name:
          type: string
        groupID:
          type: array
          items:
            type: string
        description:
          type: string
        URI:
          type: string
        type:
          type: string
      required:
        - ID
        - name
        - groupID
        - description
        - URI
    Group:
      title: Group
      type: object
      properties:
        ID:
          type: string
        name:
          type: string
      required:
        - ID
        - name
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        relatedIDs:
          type: array
          items:
            type: string
      required:
        - code
        - message
        - relatedIDs
