// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.7.0 DO NOT EDIT.
package main

// Error defines model for Error.
type Error struct {
	Code       *string   `json:"code,omitempty"`
	Message    *string   `json:"message,omitempty"`
	RelatedIDs *[]string `json:"relatedIDs,omitempty"`
}

// Feed defines model for Feed.
type Feed struct {
	ID          string   `json:"ID"`
	URI         string   `json:"URI"`
	Description string   `json:"description"`
	GroupID     []string `json:"groupID"`
	Name        string   `json:"name"`
	Type        string   `json:"type"`
}

// Group defines model for Group.
type Group struct {
	ID   string `json:"ID"`
	Name string `json:"name"`
}

// Post defines model for Post.
type Post struct {
	Content     string  `json:"content"`
	Description string  `json:"description"`
	FeedID      string  `json:"feedID"`
	ImageURL    *string `json:"imageURL,omitempty"`
	Link        string  `json:"link"`
	Title       string  `json:"title"`
}
