// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package types

// Error defines model for Error.
type Error struct {
	Code       string   `json:"code"`
	Message    string   `json:"message"`
	RelatedIDs []string `json:"relatedIDs"`
}

// Feed defines model for Feed.
type Feed struct {
	ID          string   `json:"ID"`
	URI         string   `json:"URI"`
	Description string   `json:"description"`
	GroupID     []string `json:"groupID"`
	Name        string   `json:"name"`
	Type        string   `json:"type"`
}

// Group defines model for Group.
type Group struct {
	ID   string `json:"ID"`
	Name string `json:"name"`
}

// Post defines model for Post.
type Post struct {
	ID              string   `json:"ID"`
	Content         string   `json:"content"`
	Description     string   `json:"description"`
	FeedID          string   `json:"feedID"`
	ImageURLs       []string `json:"imageURLs"`
	IsRedditGallery bool     `json:"isRedditGallery"`
	Link            string   `json:"link"`
	Permalink       string   `json:"permalink"`
	Timestamp       int      `json:"timestamp"`
	Title           string   `json:"title"`
}
