// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "github.com/bakkerme/metacomposite/v2/types"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// LoadPosts provides a mock function with given fields: feed
func (_m *Loader) LoadPosts(feed *types.Feed) (*[]types.Post, error) {
	ret := _m.Called(feed)

	var r0 *[]types.Post
	if rf, ok := ret.Get(0).(func(*types.Feed) *[]types.Post); ok {
		r0 = rf(feed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*types.Feed) error); ok {
		r1 = rf(feed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
